[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy-test = { path = "../bevy-test" }
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.21.0"
futures-util = "0.3"
